#:include view/template/dashboard.kv
#:include view/template/sidebar.kv
#:include view/template/topbar.kv

#:include view/cliente.kv

NavigationLayout:
    id: nav_layout

    Sidebar:

    BoxLayout:
        orientation: 'vertical'
        Topbar:

        ScreenManager:
            id: scr_mngr
            Screen:
                name: 'dashboard'
                Dashboard:

            Screen:
                name: 'cliente'
                Cliente:

